# Generated by Django 3.0.2 on 2020-02-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp1', '0002_auto_20200214_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='Product_id',
            field=models.IntegerField(unique=True),
        ),
    ]
